gitops:
  name: ecommerce-app
  projectIdentifier: default_project
  orgIdentifier: default
  type: application
  application:
    metadata:
      clusterName: gitops_cluster
      labels:
        harness.io/serviceRef: ecommerce-app
        harness.io/envRef: ecommerce-env
    spec:
      source:
        repoURL: https://github.com/andreizimin/ecommerce-cicd-demo
        path: kubernetes
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: ecommerce-app
  agentIdentifier: AGENT_NAME
  clusterIdentifier: gitopscluster
  repoIdentifier: gitopsrepo
